### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [vovagorodok/ble_ota_app#21]
https://gitlab.com/fdroid/fdroiddata/-/jobs/8076814723

Could you please take a look? Thanks!

**Comment by licaon-kter** [comment]
https://github.com/vovagorodok/ble_ota_app/blob/1.2.0/.github/workflows/dart.yml should have been updated to 3.24.3 @vovagorodok  did you forgot?

**Comment by vovagorodok** [comment]
Unfortunately yes. Fixed: https://github.com/vovagorodok/ble_ota_app/commit/3365c4969b5008ab78e29caa4c84def707a64111

Should I create new release?

**Comment by licaon-kter** [comment]
there are 3 more commits in between so better to use a new release when ready, imho

**Comment by vovagorodok** [comment]
Done, and thanks a lot for investigation! Added note for future: https://github.com/vovagorodok/ble_ota_app/blob/main/doc/RELEASE.md

**Comment by licaon-kter** [comment]
thanks https://gitlab.com/fdroid/fdroiddata/-/commit/677ac4529a0bf826ee07e95b548e601c19957948
