### ISSUE TITLE
Stuck on connecting

### ISSUE THREAD

**Issue by Pikokosan** [vovagorodok/ble_ota_app#6]
App shows bluetooth device but sticks on connecting 

Build info

App:
Android studio with flutter installed.

Arduinobleota:
Arduin ide with build flag to use nimble
Compiled and tried both basic example and full example.

<img src="https://user-images.githubusercontent.com/23328741/233571265-37766a40-2df8-4dff-a9b0-9424d649636a.jpg" alt="drawing" width="250"/>

**Comment by vovagorodok** [comment]
Are you using example from ArduinoBleOta or code from Your project?

**Comment by Pikokosan** [comment]
Added what I used to first post.

App code was compiled as is using android studio with flutter plugin

Firmware code was compiled in arduino ide with the build flag for nimble added. Tried both the basic and full example. No modifications to the code.

**Comment by vovagorodok** [comment]
Thanks!

I'm using VS Code with Platformio plugin. Arduino IDE wasn't tested. I'll do it later.

Issue can be in Arduino IDE compiler. Can be different than Platformio use in their toolchain.

Can I ask You to try VS Code with Platformio plugin? It will help me to eliminate where is issue

**Comment by Pikokosan** [comment]
Yes sir and sorry for the poor information in the comments. Late-night testing and was very tired.

Tonight I will try with platformio. already have it setup for my other projects.

**Comment by Pikokosan** [comment]
Tried compiling the example code for the esp32 with nimble with platformio in vscode still has the same issue of being stuck on connecting.

**Comment by vovagorodok** [comment]
Hmm,
I have this permission in manifest file:
https://github.com/vovagorodok/ble_ota_app/blob/0116ef0dd9d70739418b245d00d90b0965359929/android/app/src/main/AndroidManifest.xml#L4
Added additional request:
https://github.com/vovagorodok/ble_ota_app/commit/0116ef0dd9d70739418b245d00d90b0965359929

Where AttributionSource is located?

**Comment by Pikokosan** [comment]
Still having issues.  confirmed its not my setup. compiled another app using the flutter_reactive_ble library and was able to connect with out issues.

**Comment by vovagorodok** [comment]
Ok, lets think what happens with mobile app. 

Do you have latest version of ble_ota_app ?

**Comment by Pikokosan** [comment]
Compiled version of the app provided works. i just pulled the new version down and compiled it. confirmed it is working as well.
